# Generated by Django 5.1.5 on 2025-01-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console_api', '0003_rename_commonuser_timelogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelogin',
            name='loginTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
