# Generated by Django 5.1.5 on 2025-01-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console_api', '0006_sesiontime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesiontime',
            name='timeSession',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
